Update Discord.js to v13.0.1
MrAugu/simple-discordjs-dashboard pull request #53
Opened 2021-08-19 05:53 UTC by sujalgoel

2021-08-19 09:22 UTC, MrAugu requested changes
For the coding style; the double quotes and double spacing indentation should also.

2021-08-23 12:27 UTC, MrAugu approved these changes
The changes look good to me.

2021-08-23 12:28 UTC, MrAugu commented
Before merging this pull request, a review is still pending from @Myst82015.

2021-08-23 14:05 UTC, sujalgoel commented
> Before merging this pull request, a review is still pending from @Myst82015.

ok

2021-08-23 18:48 UTC, MrAugu commented on index.js
> +	}
We kinda should.

2021-08-23 18:48 UTC, MrAugu commented on index.js
> +	}
But at another time.

2021-08-23 18:50 UTC, Myst82015 approved these changes

2021-08-23 18:53 UTC, merged